import Head from "next/head";
import { useRouter } from 'next/router'
import Header from "../components/Header";
import SinglePost from '../components/ItemsDetail';

function ItemDetails( { data } ) {

    const router = useRouter();

    return (
        <div className="">
            <Head>
                <title>{data.title} | Hulu 2.0</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Header */}
            <Header />
            
            {/* Item Details */}
            <SinglePost result={data} />

        </div>
    )
}

export default ItemDetails

export async function getServerSideProps( context ) {
 
    const { id, type } = context.query;

    const request = await fetch(
        `https://api.themoviedb.org/3/${type}/${id}?api_key=245f87f040961c37cd1e49531bfa2f72`
    );

    const data = await request.json();

    return {
        props: {
            data
        },
    };
    
}